{{- include "common.configmap" (list . "vertex-containers.configmap") -}}
{{- define "vertex-containers.configmap" -}}
data:
  VERTEX_LOGS_ADDR: $VERTEX_LOGS_VERTEX_LOGS_SERVICE_HOST:$VERTEX_LOGS_VERTEX_LOGS_SERVICE_PORT
  VERTEX_AUTH_ADDR: $VERTEX_AUTH_VERTEX_AUTH_SERVICE_HOST:$VERTEX_AUTH_VERTEX_AUTH_SERVICE_PORT
  VERTEX_CONTAINERS_KERNEL_ADDR: $VERTEX_CONTAINERS_KERNEL_VERTEX_CONTAINERS_KERNEL_SERVICE_HOST:$VERTEX_CONTAINERS_KERNEL_VERTEX_CONTAINERS_KERNEL_SERVICE_PORT
  VERTEX_DB_HOST: {{ .Release.Name }}-postgresql
  VERTEX_DB_PORT: {{ .Values.postgresql.port | quote }}
{{- end -}}
