{{- include "common.configmap" (list . "vertex-containers.configmap") -}}
{{- define "vertex-containers.configmap" -}}
data:
  VERTEX_LOGS_ADDR: http://vertex-logs-vertex-logs-service:8080/api
  VERTEX_AUTH_ADDR: http://vertex-auth-vertex-auth-service:8080/api
  VERTEX_CONTAINERS_KERNEL_ADDR: http://vertex-containers-vertex-containers-kernel-service:8080/api
  VERTEX_DB_HOST: {{ .Release.Name }}-{{ .Chart.Name }}-postgresql
  VERTEX_DB_PORT: {{ .Values.postgresql.port | quote }}
{{- end -}}
