containers:
  - name: vertex-tunnels
    image: ghcr.io/vertex-center/vertex-tunnels:main
    ports:
      - in: 8080
        out: 30514
    envFromConfigMap: true

service:
  type: LoadBalancer
  ports:
    - port: 8080
