{{- include "common.configmap" (list . "vertex-auth.configmap") -}}
{{- define "vertex-auth.configmap" -}}
data:
  VERTEX_LOGS_ADDR: http://vertex-logs-vertex-logs-service:7016/api
  VERTEX_DB_HOST: {{ .Release.Name }}-{{ .Chart.Name }}-postgresql
  VERTEX_DB_PORT: {{ .Values.postgresql.port | quote }}
{{- end -}}
