image: ghcr.io/vertex-center/vertex-containers:main
service:
  type: LoadBalancer
  port: 30504
postgresql:
  port: 5432
  auth:
    database: containers
    username: vertex
    password: vx-pg-pass
