containers:
  - name: vertex-auth
    image: ghcr.io/vertex-center/vertex-auth:main
    ports:
      - in: 8080
        out: 30502
    envFromConfigMap: true
    envFromSecrets: true

service:
  type: LoadBalancer
  ports:
    - port: 7002
      nodePort: 30502
      targetPort: 8080

configmap:
  VERTEX_LOGS_ADDR: http://vertex-logs-vertex-logs-service:7016/api

postgresql:
  nameOverride: vertex-auth-postgresql
  port: 5432
  auth:
    database: auth
    username: vertex
    password: vx-pg-pass
