containers:
  - name: vertex-logs
    image: ghcr.io/vertex-center/vertex-logs:main
    ports:
      - in: 8080
        out: 30502
    envFromConfigMap: true

service:
  type: LoadBalancer
  ports:
    - port: 8080

postgresql:
  nameOverride: vertex-auth-postgresql
  port: 5432
  auth:
    database: auth
    username: vertex
    password: vx-pg-pass
