containers:
  - name: vertex-containers
    image: ghcr.io/vertex-center/vertex-containers:main
    ports:
      - in: 8080
        out: 30504
    envFromConfigMap: true
    envFromSecrets: true

service:
  type: LoadBalancer
  ports:
    - port: 7004
      nodePort: 30504
      targetPort: 8080

configmap:
  VERTEX_LOGS_ADDR: http://vertex-logs-vertex-logs-service:7016/api
  VERTEX_AUTH_ADDR: http://vertex-auth-vertex-auth-service:7002/api
  VERTEX_CONTAINERS_KERNEL_ADDR: http://vertex-containers-k-vertex-containers-k-service:7005/api

postgresql:
  nameOverride: vertex-containers-postgresql
  port: 5432
  auth:
    database: containers
    username: vertex
    password: vx-pg-pass
