containers:
  - name: vertex-containers
    image: ghcr.io/vertex-center/vertex-containers:main
    ports:
      - in: 8080
        out: 30504
    envFromConfigMap: true
    envFromSecrets: true

service:
  type: LoadBalancer
  ports:
    - port: 8080

postgresql:
  nameOverride: vertex-containers-postgresql
  port: 5432
  auth:
    database: containers
    username: vertex
    password: vx-pg-pass
