apiVersion: v2
name: vertex-sql
description: A Helm chart for Vertex SQL
type: application
version: 0.5.0
appVersion: "0.0.0"
dependencies:
  - name: common
    version: 0.5.0
    repository: "file://../common"
