containers:
  - name: vertex-sql
    image: ghcr.io/vertex-center/vertex-sql:main
    ports:
      - in: 8080
        out: 30512
    envFromConfigMap: true

configmap:
  VERTEX_AUTH_ADDR: http://vertex-auth-vertex-auth-service:7002/api
  VERTEX_LOGS_ADDR: http://vertex-logs-vertex-logs-service:7016/api
  VERTEX_CONTAINERS_ADDR: http://vertex-containers-vertex-containers-service:7004/api

service:
  type: LoadBalancer
  ports:
    - port: 7012
      nodePort: 30512
      targetPort: 8080
