{{- define "vxcommon.configmap.tpl" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name | printf "%s-%s" .Chart.Name }}-configmap
data: {}
{{- end -}}

{{- define "vxcommon.configmap" -}}
{{- include "vxcommon.util.merge" (append . "vxcommon.configmap.tpl") -}}
{{- end -}}
