{{- define "vxcommon.deployment.tpl" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: default
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ .Release.Name | printf "%s-%s" .Chart.Name }}-configmap
            - secretRef:
                name: {{ .Release.Name | printf "%s-%s" .Chart.Name }}-secrets
{{- end -}}

{{- define "vxcommon.deployment" -}}
{{- include "vxcommon.util.merge" (append . "vxcommon.deployment.tpl") -}}
{{- end -}}
