{{- define "vxcommon.secrets.tpl" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name | printf "%s-%s" .Chart.Name }}-secrets
data: {}
{{- end -}}

{{- define "vxcommon.secrets" -}}
{{- include "vxcommon.util.merge" (append . "vxcommon.secrets.tpl") -}}
{{- end -}}
