{{- define "common.secrets.tpl" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name | printf "%s-%s" .Chart.Name }}-secrets
data: {}
{{- end -}}

{{- define "common.secrets" -}}
{{- include "common.util.merge" (append . "common.secrets.tpl") -}}
{{- end -}}
