{{- define "vxcommon.service.tpl" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: default
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: 8080
      nodePort: {{ .Values.service.port }}
{{- end -}}

{{- define "vxcommon.service" -}}
{{- include "vxcommon.util.merge" (append . "vxcommon.service.tpl") -}}
{{- end -}}
