{{- define "common.service.tpl" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}
  ports:
    {{- range .Values.service.ports }}
    - protocol: {{ default "TCP" .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      nodePort: {{ .nodePort }}
    {{- end }}
{{- end -}}

{{- define "common.service" -}}
{{- include "common.util.merge" (append . "common.service.tpl") -}}
{{- end -}}
