{{- include "common.configmap" (list . "vertex-admin.configmap") -}}
{{- define "vertex-admin.configmap" -}}
data:
  VERTEX_AUTH_ADDR: http://vertex-auth-vertex-auth-service:7002/api
  VERTEX_LOGS_ADDR: http://vertex-logs-vertex-logs-service:7016/api
  VERTEX_DB_HOST: {{ .Release.Name }}-{{ .Chart.Name }}-postgresql
  VERTEX_DB_PORT: {{ .Values.postgresql.port | quote }}
{{- end -}}
