apiVersion: v2
name: vertex-logs
description: A Helm chart for Vertex Logs
type: application
version: 0.5.0
appVersion: "0.0.0"
dependencies:
  - name: common
    version: 0.5.0
    repository: "file://../common"
