containers:
  - name: vertex-logs
    image: ghcr.io/vertex-center/vertex-logs:main
    ports:
      - in: 8080
        out: 30516
    envFromConfigMap: true

service:
  type: LoadBalancer
  ports:
    - port: 8080
