containers:
  - name: vertex-logs
    image: ghcr.io/vertex-center/vertex-logs:main
    ports:
      - in: 8080
        out: 30516
    volumeMounts:
      - name: vertex-logs
        path: /live/logs
    envFromConfigMap: true

volumes:
  - name: vertex-logs
    path: /live/logs

service:
  type: LoadBalancer
  ports:
    - port: 7016
      nodePort: 30516
      targetPort: 8080
