name: Deploy Charts

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    name: Deploy Charts
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Vertex Nexa Bot
        run: |
          git config user.email "149347004+vertex-nexa[bot]@users.noreply.github.com"
          git config user.name "vertex-nexa[bot]"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          make install-deps
          make update-charts

      - name: Release
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: .
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
