containers:
  - name: vertex-reverseproxy
    image: ghcr.io/vertex-center/vertex-reverseproxy:main
    ports:
      - in: 8080
        out: 30508
    envFromConfigMap: true

configmap:
  VERTEX_AUTH_ADDR: http://vertex-auth-vertex-auth-service:7002/api
  VERTEX_LOGS_ADDR: http://vertex-logs-vertex-logs-service:7016/api

service:
  type: LoadBalancer
  ports:
    - port: 7008
      nodePort: 30508
      targetPort: 8080
